version: "3"

services:
  # web
  web:
    # コンテナ名
    container_name: web
    # image
    image: nginx:alpine
    # 他のコンテナ起動後に起動するように制御
    depends_on:
      - php
      - db
    # ポート開放
    ports:
      - "80:80"
    # ボリューム
    volumes:
      - "./nginx/conf.d:/etc/nginx/conf.d"
      - "./app:/var/www/html"

  # app
  php:
    # コンテナ名
    container_name: php
    # ビルド
    build: ./dockers/php
    # コンテナに入るようにできる
    tty: true
    # 他のコンテナが起動後に動くように制御
    depends_on:
      - db
    # ボリューム
    volumes:
      - "./app:/var/www/html"
    # ポート
    ports:
      - 9000:9000
      - 4321:4321
    # 環境変数
    environment:
      TZ: "Asia/Tokyo"
  # DB
  db:
    # コンテナ名
    container_name: mysql
    # イメージ
    image: mysql
    #
    tty: true
    # 再起動
    restart: always
    # 環境変数
    environment:
      MYSQL_ROOT_USER: "root"
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: sample
      MYSQL_USER: hoge
      MYSQL_PASSWORD: foofoo
      TZ: "Asia/Tokyo"
    # ボリューム
    volumes:
      - mysql_data:/var/lib/mysql
    # ポート
    ports:
      - 3306:3306

# 名前付きボリュームをdockerホストの管理下で作成
volumes:
  mysql_data: {}
